ha_gpiod:
  gpio_device_path: /dev/gpiochip0
  switches:
    - name: Switch red 1
      port: 4
      unique_id: switch_red_1
    - name: Switch red 2
      port: 22
  binary_sensors:
    - name: button
      port: 7
      bounce: 250
      bias: "UP"

